# Generated by Django 2.1.2 on 2018-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20181014_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Exchange rate to base currency'),
        ),
    ]
